### PR TITLE
Added GoogleTagManager code to main html page

### PR DESCRIPTION
**Pull request by MikeMolIS**

### CODE REVIEW

**Comment by MartinKanters** [comment]
Nice, thanks for doing this. Can you put it in a template and at the bottom of the <body> element? That keeps the code a bit cleaner.

**Comment by MikeMolIS** [comment]
I can do that, but the documentation of Google TagManager states: "Copy the code below and paste it onto every page of your website. Place it immediately after the opening <body> tag."

**Comment by MartinKanters** [comment]
Ah okay, in that case, we should put it in a template and on the top of the <body> element. :)

**Comment by analyzedgg** [comment]
I thought it should be at the top of the body(html) element, right now it is at the top of our div with id body, but let's try it out.

**Pull request merged**
